FROM golang:1.25-alpine AS builder

WORKDIR /app

ENV GO111MODULE=on

ENV CGO_ENABLED=0 
ENV GOOS=linux

COPY . .

RUN go build -mod=vendor -o engine ./cmd/engine/main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates tzdata

WORKDIR /app

COPY --from=builder /app/engine .

CMD ["./engine"]